from_latest_tag = false
tag_prefix = 'v'
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = ['master']
skip_ci = '[skip ci]'
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = 'CHANGELOG.md'
template = 'remote'
remote = 'github.com'
repository = 'codestats.nvim'
owner = 'liljaylj'
authors = [{ signature = 'Zhanibek Adilbekov', username = 'liljaylj' }]

[bump_profiles]

[packages]
