#!/usr/bin/env bash

set -Eeuo pipefail

result=0
case "$1" in
setup)
    # install git hooks
    while read -r hook; do
        if [[ -f ".git/hooks/$hook" ]]; then
            if diff --color=always -u ".git/hooks/$hook" "hooks/$hook"; then
                continue
            fi
            >&2 echo
            >&2 read -r -s -n 1 -p 'Press [Enter] to overwrite or [Ctrl+C] to cancel.' </dev/tty
            >&2 echo
        fi
        install -v -Dm755 "hooks/$hook" ".git/hooks/$hook"
    done < <(ls -1 hooks/)
    ;;
check)
    >&2 echo
    >&2 echo ':: Git hooks integrity'
    >&2 echo
    hooks_result=0
    while read -r hook; do
        if ! diff --color=always -u ".git/hooks/$hook" "hooks/$hook"; then
            hooks_result=1
            result=1
        fi
    done < <(ls -1 hooks/)
    >&2 echo
    >&2 echo ':: Lint'
    >&2 echo
    lint_result=0
    if ! selene .; then
        lint_result=1
        result=1
    fi
    >&2 echo
    >&2 echo ':: Check format'
    >&2 echo
    format_result=0
    if ! stylua -c .; then
        format_result=1
        result=1
    fi
    >&2 echo
    >&2 echo ':: Result'
    >&2 echo
    if [[ "$result" -gt 0 ]]; then
        if [[ "$hooks_result" -gt 0 ]]; then
            >&2 echo '- Please setup Git hooks with "./dev setup".'
        fi
        if [[ "$lint_result" -gt 0 ]]; then
            >&2 echo '- Check and fix linting errors.'
        fi
        if [[ "$format_result" -gt 0 ]]; then
            >&2 echo '- Format code with "stylua .".'
        fi
    else
        >&2 echo 'Everything is OK.'
    fi
    ;;
*)
    >&2 echo
    >&2 echo "$(basename "$0") <command>:"
    >&2 echo '  setup - install git hooks'
    >&2 echo '  check - lint and verify format'
    ;;
esac
exit "$result"
